/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-03-20 15:12:36 UTC)
 * on 2013-03-25 at 22:04:24 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.supersketchysketch.model;

/**
 * Model definition for SRLAssignment.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SRLAssignment extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long courseId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("srl_questionIds") @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> srlQuestionIds;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCourseId() {
    return courseId;
  }

  /**
   * @param courseId courseId or {@code null} for none
   */
  public SRLAssignment setCourseId(java.lang.Long courseId) {
    this.courseId = courseId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public SRLAssignment setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public SRLAssignment setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getSrlQuestionIds() {
    return srlQuestionIds;
  }

  /**
   * @param srlQuestionIds srlQuestionIds or {@code null} for none
   */
  public SRLAssignment setSrlQuestionIds(java.util.List<java.lang.Long> srlQuestionIds) {
    this.srlQuestionIds = srlQuestionIds;
    return this;
  }

  @Override
  public SRLAssignment set(String fieldName, Object value) {
    return (SRLAssignment) super.set(fieldName, value);
  }

  @Override
  public SRLAssignment clone() {
    return (SRLAssignment) super.clone();
  }

}
