/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-03-20 15:12:36 UTC)
 * on 2013-03-25 at 22:04:24 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.supersketchysketch.model;

/**
 * Model definition for SRLSubmission.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SRLSubmission extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long questonId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer sketch;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("srl_questionId") @com.google.api.client.json.JsonString
  private java.lang.Long srlQuestionId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("srl_userId") @com.google.api.client.json.JsonString
  private java.lang.Long srlUserId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public SRLSubmission setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getQuestonId() {
    return questonId;
  }

  /**
   * @param questonId questonId or {@code null} for none
   */
  public SRLSubmission setQuestonId(java.lang.Long questonId) {
    this.questonId = questonId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSketch() {
    return sketch;
  }

  /**
   * @param sketch sketch or {@code null} for none
   */
  public SRLSubmission setSketch(java.lang.Integer sketch) {
    this.sketch = sketch;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getSrlQuestionId() {
    return srlQuestionId;
  }

  /**
   * @param srlQuestionId srlQuestionId or {@code null} for none
   */
  public SRLSubmission setSrlQuestionId(java.lang.Long srlQuestionId) {
    this.srlQuestionId = srlQuestionId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getSrlUserId() {
    return srlUserId;
  }

  /**
   * @param srlUserId srlUserId or {@code null} for none
   */
  public SRLSubmission setSrlUserId(java.lang.Long srlUserId) {
    this.srlUserId = srlUserId;
    return this;
  }

  @Override
  public SRLSubmission set(String fieldName, Object value) {
    return (SRLSubmission) super.set(fieldName, value);
  }

  @Override
  public SRLSubmission clone() {
    return (SRLSubmission) super.clone();
  }

}
